steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nextrace-api', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nextrace-api']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'nextrace-api', '--image', 'gcr.io/$PROJECT_ID/nextrace-api', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/nextrace-api
